### ISSUE TITLE
Picture getting saved in gallary

### ISSUE THREAD

**Issue by JeevanDeep** [robertlevonyan/MediaPicker#11]
Is it Possible not save the photo in pictures folder when we open a photo from gallery?

**Comment by robertlevonyan** [comment]
No, In that case the quality is too low

**Comment by JeevanDeep** [comment]
I dont understand. If i already have a picture in my gallery why is it saving it in pictures again?

**Comment by robertlevonyan** [comment]
It shouldn't save it again, only in case of camera. I'll check it.

**Comment by JeevanDeep** [comment]
Thank you sir. Here is a video of the problem
https://drive.google.com/open?id=11oYoQCjWMyMWWlXCHNW-gy9wTZwFAMZX

**Comment by tomaszshowoff** [comment]
Hi Robert. Having similar issue - images that are taken with a camera are being saved in two different folders... Any solution to that?

Thanks

**Comment by MohammadAliK** [comment]
> Hi Robert. Having similar issue - images that are taken with a camera are being saved twice in the same folder... Any solution to that?
> 
> Thanks

I also facing this issue at the time of 29-07-2020. Have you got the solution @tomaszshowoff  @robertlevonyan

**Comment by robertlevonyan** [comment]
Please try new version! `2.0.0`
