### ISSUE TITLE
Cannot use this in Activity

### ISSUE THREAD

**Issue by rahul9hz** [robertlevonyan/MediaPicker#12]
Hi All 

I am unable to use this in Activity my app is crashing

**Comment by sagarlava** [comment]
Yes, not working from activity

**Comment by derdevil** [comment]
try this ->
pickerDialog.show(getSupportFragmentManager(), "");

**Comment by robertlevonyan** [comment]
which version are you using?

**Comment by robertlevonyan** [comment]
please try new version, if the problem still occurs I will reopen the issue.

**Comment by aasif1297** [comment]
I have tried the latest version and its still getting crash when opening my activity with this picker.
