### ISSUE TITLE
Custom item model

### ISSUE THREAD

**Issue by ismailyap** [robertlevonyan/MediaPicker#17]
Hi,
when use Custom item model background is not change.
hasBackround value is true and color value is setted but item using default color

**Comment by robertlevonyan** [comment]
you can only set a background color only for the item icon, not the entire item

**Comment by ismailyap** [comment]
I understand but item icon background not change. My code like this but icon background same. How can change icon background green
val itemModel_camera = ItemModel(
            ItemType.ITEM_CAMERA,
            item_camera_tag, 
            0,  
            true,
            ShapeType.TYPE_CIRCLE, 
            R.color.butoncolor_green      
        )

**Comment by ismailyap** [comment]
Also gallery picker always return cannot access error my test on android emulator Pixel 3 API 30

**Comment by robertlevonyan** [comment]
instead of `R.color.butoncolor_green` use `ContextCompat.getColor(context, R.color.butoncolor_green)`. The color in ItemModel is a `@ColorInt` not a `@ColorRes`.
And please test on a real device, not on emulator.
