### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by chimzycash** [robertlevonyan/MediaPicker#3]
Hello,

I came across your project and I created a logo for you, If you find it good enough and you like it, please let me know. The link contains the google drive files for your use.

https://drive.google.com/drive/folders/1dz1C_TAcp1YthiuLMdvKPCsN8OQuoDR0?usp=sharing

Regards.

![media picker logo presentation](https://user-images.githubusercontent.com/37814297/38950182-a1353f80-433c-11e8-9ac4-9c3821a12cb4.jpg)

**Comment by robertlevonyan** [comment]
Wow, it's great. Thank you so much :) All versions are awesome !!!
