### ISSUE TITLE
Having problem with calling from Java projects Fragment

### ISSUE THREAD

**Issue by forhad013** [robertlevonyan/MediaPicker#4]
PickerDialog pickerDialog = PickerDialog.Builder(this)
                .setTitle("Select")          
                .setListType(PickerDialog.TYPE_LIST)    
                .setItems(ItemModel.ITEM_GALLERY)          
                .create();

this code is showing error in Fragment.  Can anyone help?

**Comment by robertlevonyan** [comment]
What is the error?

**Comment by robertlevonyan** [comment]
in setItems() you have to pass a list of ItemModels

**Comment by iranandroid** [comment]
Hi
is it possible use this library in java project?

  PickerDialog pickerDialog = new PickerDialog.Builder(ThreadHistoryActivity.this)
          .setTitle("Select")
          .setListType(PickerDialog.ListType.TYPE_GRID,3)
          .setItems(null)
          .create();

i use this code, but create method not know

**Comment by robertlevonyan** [comment]
In kotlin there is an extension to create the dialog. The library is intended to be used in kotlin, but you can try to use it in Java as well.
