### ISSUE TITLE
OnPickerClosedListener not called

### ISSUE THREAD

**Issue by stefanopassador** [robertlevonyan/MediaPicker#6]
OnPickerClosedListener is not being called after I select a photo from Gallery or from the Camera.

**Comment by CarlosJJR** [comment]
Having same problem on Android 19. For higher APIs it works just fine.

For some reason the camera on KitKat rotates the screen and that is causing the Activity to recreate. Maybe it has something to do with that?

![demo](https://user-images.githubusercontent.com/6587434/39206363-d2203f34-47c2-11e8-9b6c-5e976e637eb5.gif)

**Comment by robertlevonyan** [comment]
Try the new version (1.1.2)

**Comment by matheusbristot** [comment]
Same problem, Android 7.1: Models Motorola device not working, record video and finish..not close dialog and return value.

**Comment by robertlevonyan** [comment]
@CarlosJJR checked on Android 4.4 (19) on HTC device works fine, version 1.1.3

**Comment by robertlevonyan** [comment]
@matheusbristot checked on Android 7.1 on Moto X device works fine, version 1.1.3
