### ISSUE TITLE
Cannot take photo or record video ?

### ISSUE THREAD

**Issue by cahyofendhi** [robertlevonyan/MediaPicker#8]
cannot take photo or record video from camera, i try using device LG, android 6
after select not open camera, always display pop up, but when to take image or video from gallery working fine

**Comment by robertlevonyan** [comment]
@cahyofendhi ?

**Comment by cahyofendhi** [comment]
@robertlevonyan 6.0,  i tried to lolipop also have error

**Comment by robertlevonyan** [comment]
please try latest version
